#server:
#    port: 8082

spring:
    profiles:
        active: prod
    data:
        mongodb:
            uri: ${MONGODB_URI}
            #database: calls_documents

    thymeleaf:
           suffix: .html
           cache: false
           encoding: UTF-8