server:
    port: 8082

spring:
    profiles:
        active: dev
    data:
        mongodb:
            uri: mongodb://localhost/calls_documents


# cd  to C:\Program Files\MongoDB\Server\4.2\bin
#enter command mongod
